name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          user: vikrant-choudhary06
          template: classic

          base: ""
          config_timezone: Asia/Kolkata

          plugin_calendar: yes
          plugin_calendar_limit: 1